os: linux
dist: bionic
sudo: required
services:
    - postgresql

language: python
python:
    - "2.7"

install:
    - bash bin/travis-build.bash
    - pip install coveralls
script:
    - sh bin/travis-run.sh
    - flake8 --count ./ckanext/biskit
    - pycodestyle --count ./ckanext/biskit
after_success:
    - coveralls
